# Generated by Django 4.1 on 2022-12-28 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BrutalBlogAdmin', '0003_post_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Tag',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='categories',
            new_name='tags',
        ),
    ]
