# Generated by Django 4.1 on 2022-12-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrutalBlogAdmin', '0005_blogpost_remove_profile_user_delete_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='id',
            field=models.CharField(default='C7885', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
