# Generated by Django 4.1 on 2022-12-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrutalBlogAdmin', '0007_alter_blogpost_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image_url',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='id',
            field=models.CharField(default='E527C', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
