# Generated by Django 4.1 on 2023-01-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrutalBlogAdmin', '0012_alter_blogpost_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='id',
            field=models.CharField(default='1DAB4', editable=False, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
