# Generated by Django 4.1 on 2023-01-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrutalBlogAdmin', '0013_alter_blogpost_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='id',
            field=models.CharField(default='F190A', editable=False, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
