# Generated by Django 4.1 on 2023-01-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrutalBlogAdmin', '0014_alter_blogpost_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='id',
            field=models.CharField(default='A3AD5', max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
