# Generated by Django 4.1 on 2023-01-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrutalBlogAdmin', '0016_alter_blogpost_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='id',
            field=models.CharField(auto_created='E7550', max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
