# Generated by Django 4.1 on 2023-01-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrutalBlogAdmin', '0017_alter_blogpost_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='id',
            field=models.UUIDField(default='DC55C', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
