# Generated by Django 4.1 on 2023-01-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrutalBlogAdmin', '0019_alter_blogpost_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='id',
            field=models.UUIDField(default='96D8A', primary_key=True, serialize=False, unique=True),
        ),
    ]
