# Generated by Django 4.1 on 2023-01-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrutalBlogAdmin', '0021_alter_blogpost_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='id',
            field=models.UUIDField(auto_created='5A43B', default='EA5BC', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
