# Generated by Django 4.1 on 2023-01-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrutalBlogAdmin', '0023_alter_blogpost_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='id',
            field=models.CharField(auto_created='D9E6A', default='1C0E2', editable=False, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
