# Generated by Django 4.1 on 2023-01-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrutalBlogAdmin', '0024_alter_blogpost_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='id_post',
            field=models.CharField(auto_created='CD349', default='76C75', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
