# Generated by Django 4.1 on 2023-01-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrutalBlogAdmin', '0025_blogpost_id_post_alter_blogpost_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='id_post',
            field=models.CharField(auto_created='CC731', default='032E7', max_length=50, unique=True),
        ),
    ]
