# Generated by Django 4.1 on 2023-01-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrutalBlogAdmin', '0026_alter_blogpost_id_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='id_post',
            field=models.CharField(auto_created='F8034', default='E949D', max_length=50, unique=True),
        ),
    ]
